name: Auto-Verify CityGrid Results
on:
  pull_request:
  push:
    paths:
      - 'output/**/*.json'
      - 'tools/verify_results.py'
      - '.github/workflows/auto_verify.yml'
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run verifier
        run: python tools/verify_results.py