name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # publish whenever you push to main
    paths:
      - 'README.md'
      - 'docs/**'
      - '.github/workflows/github-pages.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docs directory
        run: |
          # Copy README.md content to docs/index.md
          cp README.md docs/index.md
          # Ensure docs directory exists and has proper structure
          ls -la docs/

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload docs folder
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs  # this is the folder you want published

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
