name: Log Validation

on:
  push:
    paths:
      - 'logs/*.json'
      - '.github/workflows/log-validation.yml'
  pull_request:
    paths:
      - 'logs/*.json'
      - '.github/workflows/log-validation.yml'

jobs:
  validate-logs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema
        
    - name: Validate JSON logs
      run: |
        python .github/workflows/validate_logs.py
        
    - name: Display validation results
      if: always()
      run: |
        echo "Log validation completed. Check output above for any errors."